import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { MousedownProvider } from '@/Context/MousedownContext';
import { MatrixProvider } from '@/Context/MatrixContext';
import { ThemeProvider } from '@mui/material';
import { theme } from '@/Theme';
import { ContextProvider } from '@/Context';
import { cookieToInitialState } from 'wagmi';
import { config } from '../config';

import { headers } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const initialState = cookieToInitialState(config, headers().get('cookie'));

    return (
        <html lang="en">
            <MatrixProvider>
                <MousedownProvider>
                    <ThemeProvider theme={theme}>
                        <ContextProvider initialState={initialState}>
                            <body className={inter.className}>{children}</body>
                        </ContextProvider>
                    </ThemeProvider>
                </MousedownProvider>
            </MatrixProvider>
        </html>
    );
}
