'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { MousedownProvider } from '@/Context/MousedownContext';
import { MatrixProvider } from '@/Context/MatrixContext';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <MatrixProvider>
                <MousedownProvider>
                    <body className={inter.className}>{children}</body>
                </MousedownProvider>
            </MatrixProvider>
        </html>
    );
}
